server:
  port: 8000

spring:
  application:
    name: bezahlung-service
  h2:
    console:
      enabled: true
  zipkin:
    base-url: http://localhost:9411/

logging:
  file:
    path: C:/Users/ckiri/Desktop/logs/
    name: microservice.log
