server:
  port: 8001


spring:
  application:
    name: bestellung-service
  h2:
    console:
      enabled: true
  zipkin:
    base-url: http://localhost:9411/
#  zipkin:
#    enabled: false
logging:
  file:
    path: C:/Users/ckiri/Desktop/logs/
    name: microservice.log

